name: Build and Deploy to Firebase Hosting
concurrency:
  group: Production
  cancel-in-progress: true
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    name: Build ⛏ and Deploy 🚀
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Run e2e tests
        run: |
          npm run start &
          npx playwright install --with-deps
          npm run test:e2e
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SAMI_SOLITAIRE_NEXT }}
          channelId: live
          projectId: sami-solitaire-next
